LOAD DATA LOCAL INFILE 'C:/Users/jdominguez/data.csv'
INTO TABLE players
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(row_num, 
    id, 
    name, 
    age, 
    photo, 
    nationality, 
    flag, 
    overall, 
    potential, 
    club, 
    club_logo, 
    value, 
    wage, 
    special, 
    preferred_foot, 
    international_reputation, 
    weak_foot, 
    skill_moves, 
    work_rate, 
    body_type, 
    real_face, 
    position, 
    jersey_number, 
    @joined, 
    loaned_from, 
    @contract_valid_until, 
    height, 
    weight, 
    ls, 
    st, 
    rs, 
    lw, 
    lf, 
    cf, 
    rf, 
    rw, 
    lam, 
    cam, 
    ram, 
    lm,
    lcm,
    cm,
    rcm,
    rm, 
    lwb,
    ldm,
    cdm,
    rdm,
    rwb,
    lb, 
    lcb,
    cb,
    rcb,
    rb,
    crossing,
    finishing, 
    heading_accuracy, 
    short_passing, 
    volleys, dribbling, 
    curve,
    fk_accuracy,
    long_passing,
    ball_control,
    acceleration, 
    sprint_speed, 
    agility,
    reactions,
    balance, 
    shot_power, 
    jumping, 
    stamina, 
    strength, 
    long_shots, 
    aggression, 
    interceptions,
    positioning, 
    vision, 
    penalties, 
    composure,
    marking, 
    standing_tackle, 
    sliding_tackle, 
    gk_diving, 
    gk_handling, 
    gk_kicking,
    gk_positioning,
    gk_reflexes, 
    release_clause)
SET joined = str_to_date(@joined, '%b %e, %Y'),
contract_valid_until = CASE WHEN str_to_date(@contract_valid_until, '%b %e, %Y') IS NULL THEN str_to_date(@contract_valid_until, '%Y') ELSE str_to_date(@contract_valid_until, '%b %e, %Y') END; 